apiVersion: v1
kind: Service
metadata:
  name: {{ include "finora.name" . }}
  labels:
    {{- include "finora.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "finora.labels" . | nindent 4 }}
    finora.io/color: {{ .Values.deployment.color }}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "finora.name" . }}
automountServiceAccountToken: false
